[package]
name = "hnu_query_macros"
version = "3.0.1"
edition = "2024"
license = "AGPL-3.0-only"
description = "Proc-macros for hnu_query observability helpers."
repository = "https://github.com/qnxg/hnu_query"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
