[package]
name = "hnu_query_macros"
version = "0.0.1"
edition = "2024"
license = "AGPL-3.0-only"
description = "Internal proc-macros for hnu_query. Not intended for direct use."
repository = "https://github.com/qnxg/hnu_query"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
